### ISSUE TITLE
Operator logs: cannot list redisclusters.redis.k8s-operator.io at the cluster scope

### ISSUE THREAD

**Issue by mslga** [AmadeusITGroup/Redis-Operator#13] opened 2018-07-03 11:26 UTC
I've installed operator chart with HELM by yours readme step-by-step:
1. Installed go compiler
2. Installed kubectl plugin as it described in [cookbook.md](https://github.com/AmadeusITGroup/Redis-Operator/blob/master/docs/cookbook.md) 
3. Installed redis-operator 

helm install --name op chart/redis-operator
```
NAME:   op
LAST DEPLOYED: Tue Jul  3 17:10:49 2018
NAMESPACE: default
STATUS: DEPLOYED

RESOURCES:
==> v1beta1/Deployment
NAME               DESIRED  CURRENT  UP-TO-DATE  AVAILABLE  AGE
op-redis-operator  1        0        0           0          0s

==> v1beta1/ClusterRole
NAME            AGE
redis-operator  0s

==> v1beta1/ClusterRoleBinding
NAME            AGE
redis-operator  0s

==> v1/ServiceAccount
NAME            SECRETS  AGE
redis-operator  1        0s
```

kubectl version 
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.1", GitCommit:"d4ab47518836c750f9949b9e0d387f20fb92260b", GitTreeState:"archive", BuildDate:"2018-04-26T10:10:34Z", GoVersion:"go1.9.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:34:22Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```

kubectl get all 
```
NAME                                    READY     STATUS    RESTARTS   AGE
pod/op-redis-operator-b64889d49-8zpw9   1/1       Running   0          9m

NAME                 TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
service/kubernetes   ClusterIP   10.233.0.1     <none>        443/TCP        4d

NAME                                DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/op-redis-operator   1         1         1            1           9m

NAME                                          DESIRED   CURRENT   READY     AGE
replicaset.apps/op-redis-operator-b64889d49   1         1         1         9m
```

When I try to install redis-cluster chart I have an error:
```
helm install --name cluster chart/redis-cluster
Error: apiVersion "redisoperator.k8s.io/v1alpha1" in redis-cluster/templates/RedisCluster.yml is not available
```

And I encountered an error in operatior logs:
```
E0703 11:11:14.938525       1 reflector.go:205] github.com/amadeusitgroup/redis-operator/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1.RedisCluster: redisclusters.redis.k8s-operator.io is forbidden: User "system:serviceaccount:default:redis-operator" cannot list redisclusters.redis.k8s-operator.io at the cluster scope
E0703 11:11:15.941721       1 reflector.go:205] github.com/amadeusitgroup/redis-operator/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1.RedisCluster: redisclusters.redis.k8s-operator.io is forbidden: User "system:serviceaccount:default:redis-operator" cannot list redisclusters.redis.k8s-operator.io at the cluster scope
E0703 11:11:16.945293       1 reflector.go:205] github.com/amadeusitgroup/redis-operator/pkg/client/informers/externalversions/factory.go:73: Failed to list *v1.RedisCluster: redisclusters.redis.k8s-operator.io is forbidden: User "system:serviceaccount:default:redis-operator" cannot list redisclusters.redis.k8s-operator.io at the cluster scope
```
Full log is available [here](https://github.com/mslga/logs/blob/master/log-redis-operator)

**Comment by clamoriniere1A** [comment] 2018-07-03 20:14
Hi,
Thank you for reporting this issue.

Good new, I was able to reproduce it easilly. 
The root cause was that the `redisoperator/operator:latest` wasn't up-to-date and so not compatible with the `master` `HEAD` helm chart (RBAC configuration).

Now, you can retry `helm install` command and force the docker image pull from the registry.
`helm install --name cluster  --set "image.pullPolicy=Always" chart/redis-cluster`

@mslga let me know if it works now for you, if you face other issues.

Thanks and regards

**Comment by mslga** [comment] 2018-07-04 04:53
Hello, 

How it works. Thank you very much :)

I re-deployed redisoperator with Helm

> helm install --name op --set "image.pullPolicy=Always" chart/redis-operator --namespace redis

And then deployed redis cluster nodes with Helm
> helm install --name cluster --set "image.pullPolicy=Always" chart/redis-cluster --namespace redis

```
kubectl get po -n redis 
NAME                                 READY     STATUS    RESTARTS   AGE
op-redis-operator-54c8f877c9-qdtzk   1/1       Running   0          1h
rediscluster-cluster-dbn84           1/1       Running   0          1h
rediscluster-cluster-f7pnx           1/1       Running   0          1h
rediscluster-cluster-g6g87           1/1       Running   0          1h
rediscluster-cluster-lx8kv           1/1       Running   0          1h
rediscluster-cluster-qb2bv           1/1       Running   0          1h
rediscluster-cluster-spsls           1/1       Running   0          1h
```
```
kubectl exec -it rediscluster-cluster-qb2bv -n redis -- redis-cli cluster info
cluster_state:ok
cluster_slots_assigned:16384
cluster_slots_ok:16384
cluster_slots_pfail:0
cluster_slots_fail:0
cluster_known_nodes:6
cluster_size:3
cluster_current_epoch:7
cluster_my_epoch:7
cluster_stats_messages_ping_sent:14028
cluster_stats_messages_pong_sent:13913
cluster_stats_messages_meet_sent:3
cluster_stats_messages_update_sent:2
cluster_stats_messages_sent:27946
cluster_stats_messages_ping_received:13911
cluster_stats_messages_pong_received:14031
cluster_stats_messages_meet_received:2
cluster_stats_messages_received:27944
```
```
kubectl exec -it rediscluster-cluster-qb2bv -n redis -- redis-cli cluster nodes
348b7564565ade147905cc8726cd3c6aa8f3f590 10.233.64.76:6379@16379 master - 0 1530679006155 6 connected 5462-10923
d6f877df4af69299e852d18abfc6eb8cedc1078f 10.233.65.57:6379@16379 master - 0 1530679006000 3 connected 0-5461
7702fd89ee27ff9c88b9c37ae2d29b7a2d7f742a 10.233.65.58:6379@16379 slave 348b7564565ade147905cc8726cd3c6aa8f3f590 0 1530679006055 6 connected
a6df96a1cbc010ce693de1f374d3e23b9d12fd96 10.233.67.71:6379@16379 myself,master - 0 1530679005000 7 connected 10924-16383
6c3f53ec0e7b16d2f941ff843e3c7f844651dff8 10.233.64.77:6379@16379 slave a6df96a1cbc010ce693de1f374d3e23b9d12fd96 0 1530679005955 7 connected
f99e8b4e16c3c21390f1b5f31ebc24163973fccb 10.233.67.72:6379@16379 slave d6f877df4af69299e852d18abfc6eb8cedc1078f 0 1530679006054 3 connected
```
Operator logs now looks like this:
```
I0704 04:46:49.194301       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (56.450165ms
I0704 04:47:19.137845       1 controller.go:165] sync() key:redis/cluster
I0704 04:47:19.199232       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (61.331343ms
I0704 04:47:49.138136       1 controller.go:165] sync() key:redis/cluster
I0704 04:47:49.169457       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (31.278663ms
I0704 04:48:19.138626       1 controller.go:165] sync() key:redis/cluster
I0704 04:48:19.194650       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (55.893988ms
I0704 04:48:49.139048       1 controller.go:165] sync() key:redis/cluster
I0704 04:48:49.196665       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (57.559511ms
I0704 04:49:19.139523       1 controller.go:165] sync() key:redis/cluster
I0704 04:49:19.196888       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (57.306072ms
I0704 04:49:49.140089       1 controller.go:165] sync() key:redis/cluster
I0704 04:49:49.196333       1 controller.go:168] Finished syncing RedisCluster "redis/cluster" (56.099704ms
```
----------------------
How I have a problem only with my **_kubectl plugin_**
When I try to check cluster status with plugin I get an error:

```
kubectl plugin rediscluster --rc=cluster
F0704 10:52:08.050032    8106 main.go:73] unable to list rediscluster err:redisclusters.redisoperator.k8s.io "cluster" not found
goroutine 1 [running]:
github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog.stacks(0xc420356f00, 0xc4201321c0, 0x81, 0xd6)
	/home/mslga/job/projects/k8s/helm-charts/redis/redis-operator/src/github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog/glog.go:766 +0xcf
github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog.(*loggingT).output(0x168c4c0, 0xc400000003, 0xc4200ee2c0, 0x15fdd66, 0x7, 0x49, 0x0)
	/home/mslga/job/projects/k8s/helm-charts/redis/redis-operator/src/github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog/glog.go:717 +0x30f
github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog.(*loggingT).printf(0x168c4c0, 0x3, 0xf75c5d, 0x22, 0xc420171870, 0x1, 0x1)
	/home/mslga/job/projects/k8s/helm-charts/redis/redis-operator/src/github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog/glog.go:655 +0x14b
github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog.Fatalf(0xf75c5d, 0x22, 0xc420171870, 0x1, 0x1)
	/home/mslga/job/projects/k8s/helm-charts/redis/redis-operator/src/github.com/amadeusitgroup/redis-operator/vendor/github.com/golang/glog/glog.go:1145 +0x67
main.main()
	/home/mslga/job/projects/k8s/helm-charts/redis/redis-operator/src/github.com/amadeusitgroup/redis-operator/cmd/kubectl-plugin/main.go:73 +0xcd6
error: exit status 255
```

**Comment by clamoriniere1A** [comment] 2018-07-04 13:33
I think it is because you didn't specify the namespace.
in your case:
`kubectl -n redis plugin rediscluster --rc=cluster`

I have fixed several issues in the kubectl plugin in the PR #15 that is merged now. You should pull again the repository and rebuild the plugin. 

Now if the resource is not present, the execution of 'kubectl plugin rediscluster' should returns:
`No resource found`

**Comment by clamoriniere1A** [comment] 2018-07-05 06:36
@mslga great!
don't hesitate to contact me for feedback of the redis-operator or if you have other issues.

**Closed by clamoriniere1A** 2018-07-05 06:36 UTC
Labels: bug
